name: call workflow
on:
  # Manual trigger from the UI
  workflow_dispatch:
    inputs:
      message:
        description: 'call from ui'
        required: true

  # Dependency to a forking workflow
  workflow_run:
    workflows: ["dispatch workflow"]
    type:
      - complete
jobs:
  say_hi:
    runs-on: ubuntu-latest
    steps:
      - name: msg
        run: echo "Invoked by call_dispatch"
